services:
  - type: web
    name: firebase-auth-api
    runtime: node
    repo: https://github.com/master-pd/blast.git
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com
    buildCommand: npm install
    startCommand: npm start
